#!/usr/bin/env python3
"""Regenerate plugins/rompler/Source/FirHalfbandCoeffs.h.

Least-squares halfband FIR via scipy.signal.firls, odd taps snapped to zero
(their magnitude is ~1e-8; snapping keeps the polyphase structure exact at
~1e-7 relative error). Run: python3 tools/design_halfband.py
"""
import numpy as np
from scipy.signal import firls

L = 127
PASS_EDGE, STOP_EDGE = 0.22, 0.28

h = firls(L, [0.0, PASS_EDGE, STOP_EDGE, 0.5], [1.0, 1.0, 0.0, 0.0], fs=1.0)
h[1::2] = 0.0
h[(L - 1) // 2] = 0.5
even = h[0::2]

lines = [
    "#pragma once", "",
    "// Generated by tools/design_halfband.py -- do not edit.",
    f"// Least-squares halfband FIR, {L} taps, pass<{PASS_EDGE}, stop>{STOP_EDGE} (x fs).",
    "// Odd taps are exactly zero except the centre, so each polyphase is a",
    "// 64-tap FIR plus a pure delay.",
    "", "namespace aod::halfband", "{", "",
    f"inline constexpr int kTaps = {L};",
    f"inline constexpr int kCentreDelay = {(L - 1) // 4};",
    f"inline constexpr int kEvenTaps = {len(even)};", "",
    "inline constexpr float kEven[kEvenTaps] = { " + ", ".join(f"{t:.17e}f" for t in even) + " };",
    "", "} // namespace aod::halfband", "",
]
open("plugins/rompler/Source/FirHalfbandCoeffs.h", "w").write("\n".join(lines))
print("wrote plugins/rompler/Source/FirHalfbandCoeffs.h")
